[package]
name = "scursor"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "Secure cursor library with support for read and write transactions"
repository = "https://github.com/stepfunc/scursor"
readme = "README.md"





